[package]
name = "gprocess-man"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2021"
homepage = "https://github.com/golemfactory/gprocess-man"
repository = "https://github.com/golemfactory/gprocess-man"
license = "GPL-3.0"
description = "Golem Process Manager"

[dependencies]
gprocess-proto = { path = "gprocess-proto" }

[dev-dependencies]

[workspace]
members = ["gprocess-proto"]

[workspace.dependencies]
bytes = "1.7"
prost = "0.13"
prost-build = "0.13"
prost-types = "0.13"
